export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const FILTER_ARTICLE_SELECT = 'FILTER_ARTICLE_SELECT'

export const FILTER_DATE_RANGE = 'FILTER_DATE_RANGE'
